### ISSUE TITLE
require() of ES Module /[...]/three/examples/jsm/loaders/FontLoader.js from /[...]/@splinetool/loader/build/SplineLoader.cjs not supported.

### ISSUE THREAD

**Issue by didier** [stefanreifenberg/svelte-spine#1]
Upon following your example code 1:1, I couldn't get it to work in SvelteKit. Or am I missing something obvious?

<details>
<summary>
Stack trace
</summary>
<pre>
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/didier/Projects/[project-directory]/node_modules/.pnpm/three@0.141.0/node_modules/three/examples/jsm/loaders/FontLoader.js from /Users/didier/Projects/[project-directory]/node_modules/.pnpm/@splinetool+loader@0.9.69_three@0.141.0/node_modules/@splinetool/loader/build/SplineLoader.cjs not supported.
Instead change the require of FontLoader.js in /Users/didier/Projects/[project-directory]/node_modules/.pnpm/@splinetool+loader@0.9.69_three@0.141.0/node_modules/@splinetool/loader/build/SplineLoader.cjs to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/didier/Projects/[project-directory]/node_modules/.pnpm/@splinetool+loader@0.9.69_three@0.141.0/node_modules/@splinetool/loader/build/SplineLoader.cjs:942:67934)
    at async Promise.all (index 0)
    at async nodeImport (/Users/didier/Projects/[project-directory]/node_modules/.pnpm/vite@2.9.12/node_modules/vite/dist/node/chunks/dep-8f5c9290.js:50356:21)
    at async eval (/src/lib/components/Box.svelte:13:31)
    at async instantiateModule (/Users/didier/Projects/[project-directory]/node_modules/.pnpm/vite@2.9.12/node_modules/vite/dist/node/chunks/dep-8f5c9290.js:50286:9)
</pre>
</details>

[Stackblitz Reproduction](https://stackblitz.com/edit/sveltejs-kit-template-default-fxlytb?file=src/routes/index.svelte)

**Comment by didier** [comment]
Oh, placed this on the wrong repo entirely. My bad!
